services:
  - type: web
    name: telegram-channel-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main2.py
    envVars:
      - key: BOT_TOKEN
        value: YOUR_BOT_TOKEN_HERE
      - key: MONGODB_URL
        value: YOUR_MONGODB_CONNECTION_STRING
